apiVersion: apps/v1
kind: Deployment
metadata:
  name: song-recommender-app-deployment
  labels:
    app: song-recommender-app
spec:
  replicas: 1
  selector:
    matchlabels:
      app: song-recommender-app
    template:
      metadata:
        labels:
          app: song-recommender-app
      spec:
        containers:
        - name: song-recommender-app
          image: gabrielurbanin/song-recommender-server:v1.0
          ports:
          - containerPort: 5000
          volumeMounts:
          - name: song-recommender-app-volume
            mountPath: /app/model
        volumes:
        - name: song-recommender-app-volume
          persistentVolumeClaim:
            claimName: project2-pvc

