apiVersion: v1
kind: Service
metadata:
  name: song-recommender-app-service
spec:
  type: NodePort
  selector:
    app: song-recommender-app
  ports:
    - protocol: TCP
      port: 31526
      targetPort: 5000
      nodePort: 31526